global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'patient-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['patient-service:8081']

  - job_name: 'doctor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['doctor-service:8082']

  - job_name: 'appointment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['appointment-service:8083']

  - job_name: 'billing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['billing-service:8084']

  - job_name: 'prescription-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prescription-service:8085']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8086']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8087']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8091']
